apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  type: ClusterIP
  selector:
    app: post-service
  ports:
  - protocol: TCP
    port: 5000
    nodePort: 30002
    targetPort: 5000