apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: my-web-app
  ports:
  - protocol: TCP
    port: 5000        # Service port
    targetPort: 5000  # Port inside the container
    nodePort: 30001   # NodePort (between 30000-32767)